version: '3.7'
services:
  db:
    build: db
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - n1
  auth0:
    build: auth0
    ports:
    - "3010:3010"
    env_file: .env
    networks:
      - n1
  webservice:
    build: webservice
    ports:
      - "8001:8000"
    env_file: .env
    depends_on:
      - db
    networks:
      - n1
  web:
    build: web
    ports:
      - "443:443"
    env_file: .env
    depends_on:
      - db
      - webservice
    networks:
      - n1
  adminer:
    image: adminer
    ports:
      - 8002:8080
networks:
  n1:
